[package]
name = "seating_system"
version = "0.1.0"
authors = ["Chen Kang Yang <30970698+chen-ky@users.noreply.github.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
